name: Webpack Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14



      - name: Set up Git
        run: |
            git config --global user.name "DieAissatouSegula"
            git config --global user.email "dieaissatou.dieng@segula.fr"    

      - name: Install dependencies
        run: npm install
      
        

      - name: Build with Webpack
        run: npx webpack

      - name: run 
        run: npm run build


      - name: Commit and push bundle
        run: |
          git add ./dist/bundle.js
          git commit -m "Add bundle.js"
          git push https://github.com/Thiecka/test_webpack/ 


       

